#ifndef WRAPPER_CONFIG_H
#define WRAPPER_CONFIG_H

/* File regenerated by Makefile */

#define BINARY_NAME "wrapper"
#define PYTHON_VERSION "3.13.0"
#define VERSION_FILE "version.json"

#define VERSION_CHECKSUM 0

#endif /* WRAPPER_CONFIG_H */
